apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/situboo/pivotal-plugin:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/situboo/pivotal-plugin:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: pivotal-plugin
        chartPath: charts/pivotal-plugin
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/situboo/pivotal-plugin"
          image.tag: "{{.TAG}}"
